### PR TITLE
Drop Zone

### PR DESCRIPTION
**Pull request by BenKurrek**
- Restructured to allow for drops
- Refactored view functions
- Implements a fee structure
- Implements a "banking" system to prepay for storage / linkdrops

### CODE REVIEW

**Comment by mattlockyer** [comment]
Crushing it!

Recap from call:
- delete keys from contract account
- only add FT keys in ft storage callback, if attached deposit > ft storage amount * keys.length 
- add LookupSet for tokenId to NFTData
- take longest tokenID sample from client in create_drop and measure how much storage is needed, check attached_deposit * keys obvs
- nft_on_transfer puts token IDs into the LookupSet and then claim randomly takes them out and sends them to whatever key made the call

Anything else?

**Comment by BenKurrek** [comment]
Yea there's just 1 more small thing:
- make sure in ft_on_transfer that the amount is a multiple of the ft_balance

Other than that, this all sounds good and I'll fix and we can merge and then I'll start on the other type of drops

**Comment by BenKurrek** [comment]
Done:
- Require that all keys are unique when creating the drops
- Delete keys in process claim
- only add FT keys in ft storage callback, if attached deposit > ft storage amount * keys.length
- Removed unnecessary checks in ft storage resolver when refunding / removing the drop
- Added require to ensure the amount % balance = 0 (to ensure it's a multiple and also greater than the balance)
- Added Optional unordered set of token IDs and longest token ID to NFTData struct (needs to be unordered so we can get the next token when claiming via iterator). 
- Added storage for longest token ID to NFTData to allow for refunding if token IDs are less than that length.
- Removed serialization and deserialization for the NFT struct
- Added JsonNFTData struct with no token IDs to be returned and passed into functions
- Added logic for inserting new NFT data into drop and measuring storage costs / clearing the set after.
- Assert that token ID in nft_on_transfer is <= largest token ID
- Added refunds if the token ID is smaller than the largest possible token ID in nft on transfer
- Add token ID to set of tokens in NFT Data during stage 2
- Remove first token ID in unordered set when claiming NFT drop.

**Comment by mattlockyer** [comment]
Looks like this is almost done. I have some admin ideas that will make a frontend more usable, but that's likely for another PR.

WDYT? Mergeable RN?

**Pull request merged**
